// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCihNDPU7dc1_uGxwCMu3POhTffuLN7V4I',
    appId: '1:782697120614:web:7b82e45b1e74174b9ffea7',
    messagingSenderId: '782697120614',
    projectId: 'for-finance-6285f',
    authDomain: 'for-finance-6285f.firebaseapp.com',
    databaseURL: 'https://for-finance-6285f-default-rtdb.firebaseio.com',
    storageBucket: 'for-finance-6285f.appspot.com',
    measurementId: 'G-ZRDEF18LHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADZkX2f5RqLDE7qn8Gq6TQiWsiYuFVdPo',
    appId: '1:782697120614:android:ea2e508f22e9c9a29ffea7',
    messagingSenderId: '782697120614',
    projectId: 'for-finance-6285f',
    databaseURL: 'https://for-finance-6285f-default-rtdb.firebaseio.com',
    storageBucket: 'for-finance-6285f.appspot.com',
  );
}
